apiVersion: v1
kind: Pod
metadata:
  name: arkcomk8s-manifest
spec:
  containers:
  - image: noshmak/arkcomk8s
    name: arkcomk8s-manifest
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP